### ISSUE TITLE
Add RDM logo to documentation template

### ISSUE THREAD

**Issue by rjaffe** [UCBerkeleyRDM/guides_and_documentation#5]
Testing the issue tracking tool. Can I have "name-spaced" issues, such as Doc1, Doc2, etc., or Data1, Data2, ...? It doesn't seem so.

**Comment by rjaffe** [comment]
How do I assign this to someone?

**Comment by UCBerkeley-RDM** [comment]
I need to be logged in as the SPA account in order to assign a task.

**Comment by UCBerkeley-RDM** [comment]
Closing as fixed.

**Comment by UCBerkeley-RDM** [comment]
One final comment: I (rjaffe) couldn't assign the task because my role in the organization was "member." Jamie has changed my role to "Owner " so now I can.
